### ISSUE TITLE
Appreciation and Questions...

### ISSUE THREAD

**Issue by KingPixil** [akaankshr4j/Project61#1]
Hey,

This project sounds awesome! I love that I'm your inspiration :smile: 

When I saw your website, I was blown away. It looks amazing! I love the fonts, color scheme, and that animation on the right. Good job!

Also, if you use my CSS Framework ([Wing](http://usewing.ml)), I would be happy to feature you in the [Example Section](http://usewing.ml/#examples). Just read the instructions in the example section for more details.

Nice job, I can't wait!

- @KingPixil

**Comment by akaankshr4j** [comment]
Hey, thanks for everything you've said!
I will use wing in the projects I'll be making, but won't be able to use it in the home page itself since I do not have time.

**Comment by KingPixil** [comment]
Awesome! Thanks for using Wing, I hope you like in, submit your website [here](https://github.com/KingPixil/wing/issues/2)
